site_name: Hello EuroPython 2021!

theme:
  name: material
  palette:
    primary: green

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français
