site_name: Hello EuroPython 2021!

theme:
  name: material
  palette:
    primary: green

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
